---
# Source: gbapp/templates/application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: guestbook
  namespace: mcm-apps
  labels:
    app: gbapp
    chart: gbapp-0.1.0
    release: gbapp
    heritage: Tiller
spec:
  selector:
    matchExpressions:
    - key: release
      operator: In
      values:
      - gbapp
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
    
---

apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: guestbook-frontal-placement-rule
  namespace: mcm-apps
  labels:
    app: gbapp
    release: gbapp
    heritage: Tiller
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev    

---

apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: guestbook-frontal
  namespace: mcm-apps
spec:
    type: GitHub
    pathname: https://github.com/jxadro/democp4mm.git
    
---

apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: guestbook-frontal
  namespace: mcm-apps
  labels:
    release: gbapp
spec:
  channel: mcm-apps/guestbook-frontal
  placement:
    placementRef:
      name: guestbook-frontal-placement-rule
      kind: PlacementRule
      group: app.ibm.com
    local: false    
  packageFilter:
    filterRef:
      name: guestbook-frontal-filter-configmap 
---

apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: guestbook-redis
  namespace: mcm-apps
spec:
    type: GitHub
    pathname: https://github.com/jxadro/democp4mm.git
    
---

apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: guestbook-redis
  namespace: mcm-apps
  labels:
    release: gbapp
spec:
  channel: mcm-apps/guestbook-redis
  placement:
    placementRef:
      name: guestbook-frontal-placement-rule
      kind: PlacementRule
      group: app.ibm.com
    local: false    
  packageFilter:
    filterRef:
      name: guestbook-redis-filter-configmap
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-frontal-filter-configmap
  namespace: mcm-apps
  labels: 
    release: gbapp
data:
    path: mcm-guestbook
    
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-redis-filter-configmap
  namespace: mcm-apps
  labels: 
    release: gbapp
data:
    path: mcm-guestbook-redis
