kind: Deployment
apiVersion: apps/v1
metadata:
  name: redismaster-dep
spec:
  selector:
    matchLabels:
      app: gbchn
      release: gbchn
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gbchn
        release: gbchn
        role: master
        tier: backend
    spec:
      containers:
        - name: redis
          image: "gcr.io/kubernetes-e2e-test-images/redis:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
