kind: Service
apiVersion: v1
metadata:
  name: redisslave-srv
  namespace: mcm-guestbook
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: gbchn
    release: gbchn
    role: slave
    tier: backend

